### ISSUE TITLE
ERROR - missing indentation for { - this is now fixed please see how to get new TagUI

### ISSUE THREAD

**Issue by Rudyefect** [aimakerspace/TagUI-Bricks#2]
ERROR - number of step { does not tally with with }

**Comment by kensoh** [comment]
Hi @Rudyefect thanks for raising this! Can you tell me which workflow that you are running, and using which TagUI version?

You can check version by typing `tagui` from command prompt to see the version you are using.

**Comment by kensoh** [comment]
Sorry for late reply, just realised I didn't subscribed to issues posted here.

Now I have subscribed and would see a notification whenever new issues are posted here.

**Comment by haiming2101** [comment]
using tagui v6.14
when try the sample workflow DBS-Forex-Gmail in Windows 10 command prompt:
C:\tagui\flows\DBS-Forex-Gmail>tagui forex_gmail.tag

it returned an error:
ERROR - missing indentation for {
ERROR - automation aborted due to above

may I know what is the problem with this?

thanks!

**Comment by kensoh** [comment]
Hi @haiming2101 , sorry for the issue! Can you remove the curly brackets `{` and `}` in the example, and also download the latest version of TagUI using this https://github.com/kelaberetiv/TagUI/issues/966#issuecomment-798784313

In TagUI v6, there is some change in the syntax and the curly brackets are no longer used. I'll work on updating the examples in this repository. Sorry for the trouble!

**Comment by haiming2101** [comment]
It works when I removed the curly brackets. it will be good to let the new users know about this change, I did some search but didn't find any clue.

Thanks!

**Comment by kensoh** [comment]
Yes the change in on TagUI homepage - https://github.com/kelaberetiv/TagUI#if-and-loop-code-blocks-can-use-indentation-instead-of-curly-braces- but the change hasn't been updated in the examples here.

**Comment by haiming2101** [comment]
that's great. thanks!

**Comment by kensoh** [comment]
Thanks for alerting me, I'll update these examples soon!

**Comment by kensoh** [comment]
Hi @haiming2101, I found a bug where pre-v6 workflows using curly brackets {} will trigger a workflow self-check condition.  

Thanks for your feedback! This is now fixed, so that this self-checking error will not show up incorrectly.

Users can download the latest copy of TagUI from here and unzip to overwrite your existing installation (please drag the folders under tagui\src to overwrite your existing installation) - https://github.com/kelaberetiv/TagUI/archive/master.zip

In the next release, this fix will become part of the packaged zip files.

**Comment by kensoh** [comment]
TagUI next release is published - https://tagui.readthedocs.io/en/latest/setup.html
